apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        # Raw config from ConfigMap
        - name: nginx-config-raw
          configMap:
            name: nginx-config

        # Shared volume for processed config
        - name: nginx-config-shared
          emptyDir: {}

        # Persistent app data
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-data-pvc

      containers:
        #  Sidecar: manages config
        - name: config-sidecar
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Copying nginx config..."
              cp /raw/nginx.conf /shared/nginx.conf
              while true; do
                sleep 30
              done
          volumeMounts:
            - name: nginx-config-raw
              mountPath: /raw
            - name: nginx-config-shared
              mountPath: /shared

        #  Main Nginx container
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            # Final config used by Nginx
            - name: nginx-config-shared
              mountPath: /etc/nginx

            # Persistent HTML content
            - name: app-storage
              mountPath: /usr/share/nginx/html
