apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config-raw
          configMap:
            name: nginx-config

        - name: nginx-config-shared
          emptyDir: {}

        - name: app-storage
          persistentVolumeClaim:
            claimName: app-data-pvc

      containers:
        - name: config-sidecar
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Copying nginx config..."
              cp /raw/nginx.conf /shared/nginx.conf
              while true; do sleep 30; done
          volumeMounts:
            - name: nginx-config-raw
              mountPath: /raw
            - name: nginx-config-shared
              mountPath: /shared

        - name: nginx
          image: 753093280022.dkr.ecr.ap-northeast-1.amazonaws.com/myrepo:IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-shared
              mountPath: /etc/nginx

            #  PVC mounted to /data instead of html folder
            - name: app-storage
              mountPath: /data
